In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [24]:
df = pd.read_csv('C://Users//Admin//Desktop//Python//Home prices in Monroe Township NJ (USA).csv')

In [25]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [26]:
df.bedrooms.median()

3.5

In [29]:
import math

print('pi is', math.pi)
print('cos(pi) is', math.cos(math.pi))

pi is 3.141592653589793
cos(pi) is -1.0


In [32]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [33]:
df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [35]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [36]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [37]:
reg = linear_model.LinearRegression()

In [38]:
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [39]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [40]:
reg.intercept_

383724.9999999998

In [41]:
reg.predict([[3000,3,40]])

array([444400.])

In [42]:
reg.predict([[3000,3,15]])

array([615025.])

In [43]:
137.25*3000+-26025.*3+-6825.*40+383724.9999999998

444399.9999999998

In [44]:
reg.predict([[2500,4,5]])

array([588625.])